### ISSUE TITLE
multiple monitor setup

### ISSUE THREAD

**Issue by HermanRas** [gregbeck/powershell-screensaver-builder#1]
Hi, your script works great, but I am running into a problem with multiple monitors using different resolutions. 
![image](https://github.com/gregbeck/powershell-screensaver-builder/assets/38083493/5cd4036d-bdb7-41ef-98fb-af737bcb0886)

I am more than willing to assist with trouble shooting.

**Comment by HermanRas** [comment]
The problem is linked to display scale, setting scale to 100% works.
![image](https://github.com/gregbeck/powershell-screensaver-builder/assets/38083493/37f057de-69c5-4d36-96f6-792f892ddad9)

**Comment by gregbeck** [comment]
It has been a long time since I looked at this.  I am guessing I didn't handle scaling at all.  I will see what I can do.

**Comment by gregbeck** [comment]
I added an app manifest to turn off DPI awareness. In my quick testing it seem to fix the issue with multiple monitors with different scales.  Can you give it a try to see if it fixes the issue you were running into?

**Comment by HermanRas** [comment]
Thank you, 

Will test and revert Tomorrow

**Comment by HermanRas** [comment]
Thanks you, I have tested on multpile computer and laptops its working 100%.

thanks for the amazing support.
